### ISSUE TITLE
JAVA exception when running alyx.getToken on alyx-dev

### ISSUE THREAD

**Issue by peterzh** [cortex-lab/alyx-matlab#24]
I receive the following error when trying to get a login token for alyx-dev ('https://alyx-dev.cortexlab.net'). The error doesn't happen when connecting to the normal alyx server ('https://alyx.cortexlab.net')

```
>> myAlyx = alyx.getToken('https://alyx-dev.cortexlab.net', _<username here>_, _<password here>_);
Error using http.jsonPost (line 31)
Java exception occurred:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.ssl.Alerts.getSSLException(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)

	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)

	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)

	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)

	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)

	at sun.security.ssl.Handshaker.processLoop(Unknown Source)

	at sun.security.ssl.Handshaker.process_record(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

	at net.psexton.ext.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:290)

	at net.psexton.ext.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)

	at net.psexton.ext.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)

	at net.psexton.ext.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)

	at net.psexton.ext.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)

	at net.psexton.ext.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)

	at net.psexton.ext.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)

	at net.psexton.ext.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)

	at net.psexton.ext.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)

	at net.psexton.ext.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)

	at net.psexton.ext.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)

	at net.psexton.ext.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)

	at net.psexton.missinghttp.MatlabShim.jsonPost(MatlabShim.java:209)

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)

	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)

	at sun.security.validator.Validator.validate(Unknown Source)

	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)

	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)

	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)

	... 21 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)

	at java.security.cert.CertPathBuilder.build(Unknown Source)

	... 27 more


Error in alyx.getToken (line 16)
    [statusCode, responseBody] = http.jsonPost([baseURL, '/auth-token/'], ['{"username":"', username, '","password":"', password, '"}']);
```

**Comment by rossant** [comment]
I think this is due to this: https://github.com/cortex-lab/alyx/issues/282#issuecomment-300526425
The REST API doesn't work with Matlab on alyx-dev because alyx-dev uses a Letsencrypt SSL certificate (incompatible with Matlab) whereas alyx uses another (paid) certificate that works with Matlab.

I don't think we can fix this without buying another SSL certificate (@nippoo?)
Otherwise we just have to wait until alyx is updated, which should be Monday morning unless you need it sooner. In that case we need to find a time where no one uses alyx so that if there is a downtime it doesn't affect users too much.

**Comment by nsteinme** [comment]
How much were the certificates? It would be sensible to be able to test
things on alyx-dev, that's the whole point after all. Especially with the
rest api where there's a bit higher risk of writing some code that does
something crazy, since we're doing POSTs sometimes.

**Comment by rossant** [comment]
See https://uk.godaddy.com/web-security/ssl-certificate
We can buy another certificate for just 1 website. There are also options to buy 1 certificate for all `*.cortexlab.net` websites but it's much more expensive. Maybe let's wait for @nippoo's opinion first.

**Comment by nsteinme** [comment]
Happy to wait to hear what @nippoo thinks but I'm sure @kdharris101 will say that £45/year is well within lab budget :)

**Comment by rossant** [comment]
Sure, but is it worth buying the plan with 5 websites for 89 pounds instead? Are we ever going to need more than 2? I don't know...

**Comment by nippoo** [comment]
I normally buy wildcard certificates (*.cortexlab.net). But LetsEncrypt is fine for all actual websites, it's just the API we need an old-school cert for.

So yeah I would just buy one more cert at £45/year. Unless people already have plans to build their own APIs for other things in the future.

**Comment by kdharris101** [comment]
We can certainly stretch to £89 also

Sent from my iPhone

On Jun 8, 2017, at 6:30 PM, Max Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


I normally buy wildcard certificates (*.cortexlab.net<http://cortexlab.net>). But LetsEncrypt is fine for all actual websites, it's just the API we need an old-school cert for.

So yeah I would just buy one more cert at £45/year. Unless people already have plans to build their own APIs for other things in the future.

**Comment by nippoo** [comment]
At some point this should be fixed. If I can find some free time in the next few months I'll fix https://github.com/psexton/missing-http/issues/9 and bundle up a new version so we can use LE certs instead!

Anyway, whatever - I'd say just get one more certificate. If we need another one we only lose £1/year! ;)

**Comment by nsteinme** [comment]
resolved with new certificate, works now -
